### ISSUE TITLE
kontextbasierte Schlüsselwörter

### ISSUE THREAD

**Issue by fwehn** [lulugo19/GermanSkript#4]
Es soll möglich sein "Verb gebe ... zurück" ("gebe zurück") als Namen zu verwenden.

**Comment by lulugo19** [comment]
Ich habe es gerade implementiert.
siehe: 1205abe8dd1488f49075d9fc85c9a8a8c0753c19

Ich habe gerade nochmal nachgedacht und habe bemerkt, dass es vielleicht doch keine so gute Idee ist.
Sei diese Funktion definiert:
```
Verb(Zeichenfolge) gebe die Zeichenfolge zurück: gebe die Zeichenfolge zurück.

die Zeichenfolge ist gebe die Zeichenfolge "Hallo" zurück
schreibe die Zeichenfolge // Hallo
```

Der Funktionskörper `gebe die Zeichenfolge zurück` der Funktion ist zweideutig:
1. es kann damit die Zurückgabe gemeint werden
2. oder der rekursive Aufruf der selben Funktion

Gerade ist es so implementiert, dass es immer als Zurückgabe erkannt wird.

Die Funktionaufruf `gebe die Zeichenfolge zurück` kann nur als Ausdruck und nicht als Satz erkannt werden.
Wenn der Funktionsaufruf mit `gebe die Zeichenfolge "Hallo" zurück` ausgeführt werden soll, wird dieser Satz nicht
als Funktionsaufruf, sondern als Rückgabe erkannt.

Außerdem wird dadurch das Syntax-Highlighting erschwert, da Schlüsselwörter abhängig vom Kontext sind.
